name = "radish"
version = "0.10.0"

description = "A Redis client for Gleam"
gleam = ">= 0.32.0"
licences = ["Apache-2.0"]
links = [
  {title = "Gleam", href = "https://gleam.run"},
  {title = "Redis", href = "https://redis.io"},
]
repository = {type = "github", user = "massivefermion", repo = "radish"}

internal_modules = [
  "radish/tcp",
  "radish/resp",
  "radish/utils",
  "radish/client",
  "radish/encoder",
  "radish/decoder",
  "radish/command",
  "radish/command/*",
]

[dependencies]
gleam_erlang = "~> 0.23"
gleam_otp = "~> 0.8"
gleam_stdlib = "~> 0.32"
mug = "~> 0.2"

[dev-dependencies]
gleeunit = "~> 1.0"
